// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantWebDAL;

#nullable disable

namespace RestaurantWebDAL.Migrations
{
    [DbContext(typeof(RestaurantWebDbContext))]
    partial class RestaurantWebDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RestaurantWebDAL.Models.Allergen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameLocalizationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NumberLocalizationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("NameLocalizationCode")
                        .IsUnique();

                    b.HasIndex("NumberLocalizationCode")
                        .IsUnique();

                    b.ToTable("Allergen");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "gluten",
                            NameLocalizationCode = "gluten-name",
                            NumberLocalizationCode = "gluten-number"
                        },
                        new
                        {
                            Id = 2,
                            Name = "crustaceans",
                            NameLocalizationCode = "crustaceans-name",
                            NumberLocalizationCode = "crustaceans-number"
                        },
                        new
                        {
                            Id = 4,
                            Name = "eggs",
                            NameLocalizationCode = "eggs-name",
                            NumberLocalizationCode = "eggs-number"
                        },
                        new
                        {
                            Id = 8,
                            Name = "fish",
                            NameLocalizationCode = "fish-name",
                            NumberLocalizationCode = "fish-number"
                        },
                        new
                        {
                            Id = 16,
                            Name = "peanuts",
                            NameLocalizationCode = "peanuts-name",
                            NumberLocalizationCode = "peanuts-number"
                        },
                        new
                        {
                            Id = 32,
                            Name = "soybeans",
                            NameLocalizationCode = "soybeans-name",
                            NumberLocalizationCode = "soybeans-number"
                        },
                        new
                        {
                            Id = 64,
                            Name = "milk",
                            NameLocalizationCode = "milk-name",
                            NumberLocalizationCode = "milk-number"
                        },
                        new
                        {
                            Id = 128,
                            Name = "nuts",
                            NameLocalizationCode = "nuts-name",
                            NumberLocalizationCode = "nuts-number"
                        },
                        new
                        {
                            Id = 256,
                            Name = "celery",
                            NameLocalizationCode = "celery-name",
                            NumberLocalizationCode = "celery-number"
                        },
                        new
                        {
                            Id = 512,
                            Name = "mustard",
                            NameLocalizationCode = "mustard-name",
                            NumberLocalizationCode = "mustard-number"
                        },
                        new
                        {
                            Id = 1024,
                            Name = "sesame-seeds",
                            NameLocalizationCode = "sesame-seeds-name",
                            NumberLocalizationCode = "sesame-seeds-number"
                        },
                        new
                        {
                            Id = 2048,
                            Name = "sulphur",
                            NameLocalizationCode = "sulfur-name",
                            NumberLocalizationCode = "sulfur-number"
                        },
                        new
                        {
                            Id = 4096,
                            Name = "lupin",
                            NameLocalizationCode = "lupin-name",
                            NumberLocalizationCode = "lupin-number"
                        },
                        new
                        {
                            Id = 8192,
                            Name = "molluscs",
                            NameLocalizationCode = "molluscs-name",
                            NumberLocalizationCode = "molluscs-number"
                        });
                });

            modelBuilder.Entity("RestaurantWebDAL.Models.DailyMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int?>("MealId")
                        .HasColumnType("int");

                    b.Property<decimal>("MenuPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("WeeklyMenuId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.HasIndex("WeeklyMenuId");

                    b.ToTable("DailyMenu");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DayOfWeek = 1,
                            MealId = 1,
                            MenuPrice = 6.5m,
                            WeeklyMenuId = 1
                        },
                        new
                        {
                            Id = 2,
                            DayOfWeek = 1,
                            MealId = 2,
                            MenuPrice = 6.5m,
                            WeeklyMenuId = 1
                        },
                        new
                        {
                            Id = 3,
                            DayOfWeek = 1,
                            MealId = 2,
                            MenuPrice = 6.5m,
                            WeeklyMenuId = 2
                        },
                        new
                        {
                            Id = 4,
                            DayOfWeek = 2,
                            MealId = 2,
                            MenuPrice = 7.0m,
                            WeeklyMenuId = 2
                        });
                });

            modelBuilder.Entity("RestaurantWebDAL.Models.Drink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<decimal>("Volume")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Drink");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kofola",
                            Price = 0.3m,
                            RestaurantId = 1,
                            Volume = 0.1m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pilsner Urquell",
                            Price = 2m,
                            RestaurantId = 1,
                            Volume = 0.5m
                        });
                });

            modelBuilder.Entity("RestaurantWebDAL.Models.Localization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IsoLanguageCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("LocalizedString")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("StringCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Localization");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Prihlásiť sa",
                            StringCode = "login"
                        },
                        new
                        {
                            Id = 68,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Ahoj",
                            StringCode = "greetings"
                        },
                        new
                        {
                            Id = 72,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Odhlásiť sa",
                            StringCode = "logout"
                        },
                        new
                        {
                            Id = 75,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Domov",
                            StringCode = "home"
                        },
                        new
                        {
                            Id = 76,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Denné menu",
                            StringCode = "daily-menu"
                        },
                        new
                        {
                            Id = 77,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Nápoje",
                            StringCode = "drinks"
                        },
                        new
                        {
                            Id = 78,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Jedlá",
                            StringCode = "meals"
                        },
                        new
                        {
                            Id = 138,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Týždenné menu",
                            StringCode = "weekly-menu"
                        },
                        new
                        {
                            Id = 400,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Vymazať",
                            StringCode = "delete"
                        },
                        new
                        {
                            Id = 401,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Upraviť",
                            StringCode = "edit"
                        },
                        new
                        {
                            Id = 402,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Späť",
                            StringCode = "back"
                        },
                        new
                        {
                            Id = 403,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Detaily",
                            StringCode = "details"
                        },
                        new
                        {
                            Id = 404,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Ste si istý že si prajete zmazať túto položku?",
                            StringCode = "confirm-delete"
                        },
                        new
                        {
                            Id = 405,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Vytvoriť",
                            StringCode = "create"
                        },
                        new
                        {
                            Id = 2,
                            IsoLanguageCode = "en",
                            LocalizedString = "Login",
                            StringCode = "login"
                        },
                        new
                        {
                            Id = 92,
                            IsoLanguageCode = "en",
                            LocalizedString = "Logout",
                            StringCode = "logout"
                        },
                        new
                        {
                            Id = 88,
                            IsoLanguageCode = "en",
                            LocalizedString = "Hello",
                            StringCode = "greetings"
                        },
                        new
                        {
                            Id = 95,
                            IsoLanguageCode = "en",
                            LocalizedString = "Home",
                            StringCode = "home"
                        },
                        new
                        {
                            Id = 96,
                            IsoLanguageCode = "en",
                            LocalizedString = "Daily menu",
                            StringCode = "daily-menu"
                        },
                        new
                        {
                            Id = 97,
                            IsoLanguageCode = "en",
                            LocalizedString = "Drinks",
                            StringCode = "drinks"
                        },
                        new
                        {
                            Id = 98,
                            IsoLanguageCode = "en",
                            LocalizedString = "Meals",
                            StringCode = "meals"
                        },
                        new
                        {
                            Id = 137,
                            IsoLanguageCode = "en",
                            LocalizedString = "Weekly Menu",
                            StringCode = "weekly-menu"
                        },
                        new
                        {
                            Id = 450,
                            IsoLanguageCode = "en",
                            LocalizedString = "Delete",
                            StringCode = "delete"
                        },
                        new
                        {
                            Id = 451,
                            IsoLanguageCode = "en",
                            LocalizedString = "Edit",
                            StringCode = "edit"
                        },
                        new
                        {
                            Id = 452,
                            IsoLanguageCode = "en",
                            LocalizedString = "Back",
                            StringCode = "back"
                        },
                        new
                        {
                            Id = 453,
                            IsoLanguageCode = "en",
                            LocalizedString = "Details",
                            StringCode = "details"
                        },
                        new
                        {
                            Id = 454,
                            IsoLanguageCode = "en",
                            LocalizedString = "Are you sure you wish to delete this?",
                            StringCode = "confirm-delete"
                        },
                        new
                        {
                            Id = 455,
                            IsoLanguageCode = "en",
                            LocalizedString = "Create",
                            StringCode = "create"
                        },
                        new
                        {
                            Id = 3,
                            IsoLanguageCode = "sk",
                            LocalizedString = "1",
                            StringCode = "gluten-number"
                        },
                        new
                        {
                            Id = 4,
                            IsoLanguageCode = "sk",
                            LocalizedString = "lepok",
                            StringCode = "gluten-name"
                        },
                        new
                        {
                            Id = 5,
                            IsoLanguageCode = "sk",
                            LocalizedString = "2",
                            StringCode = "crustaceans-number"
                        },
                        new
                        {
                            Id = 6,
                            IsoLanguageCode = "sk",
                            LocalizedString = "kôrovce",
                            StringCode = "crustaceans-name"
                        },
                        new
                        {
                            Id = 7,
                            IsoLanguageCode = "sk",
                            LocalizedString = "3",
                            StringCode = "eggs-number"
                        },
                        new
                        {
                            Id = 8,
                            IsoLanguageCode = "sk",
                            LocalizedString = "vajcia",
                            StringCode = "eggs-name"
                        },
                        new
                        {
                            Id = 9,
                            IsoLanguageCode = "sk",
                            LocalizedString = "4",
                            StringCode = "fish-number"
                        },
                        new
                        {
                            Id = 10,
                            IsoLanguageCode = "sk",
                            LocalizedString = "ryby",
                            StringCode = "fish-name"
                        },
                        new
                        {
                            Id = 11,
                            IsoLanguageCode = "sk",
                            LocalizedString = "5",
                            StringCode = "peanuts-number"
                        },
                        new
                        {
                            Id = 12,
                            IsoLanguageCode = "sk",
                            LocalizedString = "podzemnica olejná (arašidy)",
                            StringCode = "peanuts-name"
                        },
                        new
                        {
                            Id = 13,
                            IsoLanguageCode = "sk",
                            LocalizedString = "6",
                            StringCode = "soybeans-number"
                        },
                        new
                        {
                            Id = 14,
                            IsoLanguageCode = "sk",
                            LocalizedString = "sójové bôby (sója)",
                            StringCode = "soybeans-name"
                        },
                        new
                        {
                            Id = 15,
                            IsoLanguageCode = "sk",
                            LocalizedString = "7",
                            StringCode = "milk-number"
                        },
                        new
                        {
                            Id = 16,
                            IsoLanguageCode = "sk",
                            LocalizedString = "mlieko",
                            StringCode = "milk-name"
                        },
                        new
                        {
                            Id = 17,
                            IsoLanguageCode = "sk",
                            LocalizedString = "8",
                            StringCode = "nuts-number"
                        },
                        new
                        {
                            Id = 18,
                            IsoLanguageCode = "sk",
                            LocalizedString = "škrupinové plody",
                            StringCode = "nuts-name"
                        },
                        new
                        {
                            Id = 19,
                            IsoLanguageCode = "sk",
                            LocalizedString = "9",
                            StringCode = "celery-number"
                        },
                        new
                        {
                            Id = 20,
                            IsoLanguageCode = "sk",
                            LocalizedString = "zeler",
                            StringCode = "celery-name"
                        },
                        new
                        {
                            Id = 21,
                            IsoLanguageCode = "sk",
                            LocalizedString = "10",
                            StringCode = "mustard-number"
                        },
                        new
                        {
                            Id = 22,
                            IsoLanguageCode = "sk",
                            LocalizedString = "horčica",
                            StringCode = "mustard-name"
                        },
                        new
                        {
                            Id = 23,
                            IsoLanguageCode = "sk",
                            LocalizedString = "11",
                            StringCode = "sesame-seeds-number"
                        },
                        new
                        {
                            Id = 24,
                            IsoLanguageCode = "sk",
                            LocalizedString = "sezamové semená (sezam)",
                            StringCode = "sesame-seeds-name"
                        },
                        new
                        {
                            Id = 25,
                            IsoLanguageCode = "sk",
                            LocalizedString = "12",
                            StringCode = "sulfur-number"
                        },
                        new
                        {
                            Id = 26,
                            IsoLanguageCode = "sk",
                            LocalizedString = "oxid siričitý a siričitany",
                            StringCode = "sulfur-name"
                        },
                        new
                        {
                            Id = 27,
                            IsoLanguageCode = "sk",
                            LocalizedString = "13",
                            StringCode = "lupin-number"
                        },
                        new
                        {
                            Id = 28,
                            IsoLanguageCode = "sk",
                            LocalizedString = "vlčí bôb (lupina)",
                            StringCode = "lupin-name"
                        },
                        new
                        {
                            Id = 29,
                            IsoLanguageCode = "sk",
                            LocalizedString = "14",
                            StringCode = "molluscs-number"
                        },
                        new
                        {
                            Id = 30,
                            IsoLanguageCode = "sk",
                            LocalizedString = "mäkkýše",
                            StringCode = "molluscs-name"
                        },
                        new
                        {
                            Id = 31,
                            IsoLanguageCode = "en",
                            LocalizedString = "1",
                            StringCode = "gluten-number"
                        },
                        new
                        {
                            Id = 32,
                            IsoLanguageCode = "en",
                            LocalizedString = "Cereals containing gluten",
                            StringCode = "gluten-name"
                        },
                        new
                        {
                            Id = 33,
                            IsoLanguageCode = "en",
                            LocalizedString = "2",
                            StringCode = "crustaceans-number"
                        },
                        new
                        {
                            Id = 34,
                            IsoLanguageCode = "en",
                            LocalizedString = "Crustaceans and products thereof",
                            StringCode = "crustaceans-name"
                        },
                        new
                        {
                            Id = 35,
                            IsoLanguageCode = "en",
                            LocalizedString = "3",
                            StringCode = "eggs-number"
                        },
                        new
                        {
                            Id = 36,
                            IsoLanguageCode = "en",
                            LocalizedString = "Eggs and products thereof",
                            StringCode = "eggs-name"
                        },
                        new
                        {
                            Id = 37,
                            IsoLanguageCode = "en",
                            LocalizedString = "4",
                            StringCode = "fish-number"
                        },
                        new
                        {
                            Id = 38,
                            IsoLanguageCode = "en",
                            LocalizedString = "Fish and products thereof",
                            StringCode = "fish-name"
                        },
                        new
                        {
                            Id = 39,
                            IsoLanguageCode = "en",
                            LocalizedString = "5",
                            StringCode = "peanuts-number"
                        },
                        new
                        {
                            Id = 40,
                            IsoLanguageCode = "en",
                            LocalizedString = "Peanuts and products thereof",
                            StringCode = "peanuts-name"
                        },
                        new
                        {
                            Id = 41,
                            IsoLanguageCode = "en",
                            LocalizedString = "6",
                            StringCode = "soybeans-number"
                        },
                        new
                        {
                            Id = 42,
                            IsoLanguageCode = "en",
                            LocalizedString = "Soybeans and products thereof",
                            StringCode = "soybeans-name"
                        },
                        new
                        {
                            Id = 43,
                            IsoLanguageCode = "en",
                            LocalizedString = "7",
                            StringCode = "milk-number"
                        },
                        new
                        {
                            Id = 44,
                            IsoLanguageCode = "en",
                            LocalizedString = "Milk and products thereof (including lactose)",
                            StringCode = "milk-name"
                        },
                        new
                        {
                            Id = 45,
                            IsoLanguageCode = "en",
                            LocalizedString = "8",
                            StringCode = "nuts-number"
                        },
                        new
                        {
                            Id = 46,
                            IsoLanguageCode = "en",
                            LocalizedString = "Nuts",
                            StringCode = "nuts-name"
                        },
                        new
                        {
                            Id = 47,
                            IsoLanguageCode = "en",
                            LocalizedString = "9",
                            StringCode = "celery-number"
                        },
                        new
                        {
                            Id = 48,
                            IsoLanguageCode = "en",
                            LocalizedString = "Celery and products thereof",
                            StringCode = "celery-name"
                        },
                        new
                        {
                            Id = 49,
                            IsoLanguageCode = "en",
                            LocalizedString = "10",
                            StringCode = "mustard-number"
                        },
                        new
                        {
                            Id = 50,
                            IsoLanguageCode = "en",
                            LocalizedString = "Mustard and products thereof",
                            StringCode = "mustard-name"
                        },
                        new
                        {
                            Id = 51,
                            IsoLanguageCode = "en",
                            LocalizedString = "11",
                            StringCode = "sesame-seeds-number"
                        },
                        new
                        {
                            Id = 52,
                            IsoLanguageCode = "en",
                            LocalizedString = "Sesame seeds and products thereof",
                            StringCode = "sesame-seeds-name"
                        },
                        new
                        {
                            Id = 53,
                            IsoLanguageCode = "en",
                            LocalizedString = "12",
                            StringCode = "sulfur-number"
                        },
                        new
                        {
                            Id = 54,
                            IsoLanguageCode = "en",
                            LocalizedString = "Sulphur dioxide and sulphites at concentrations of more than 10 mg/kg or 10 mg/litre",
                            StringCode = "sulfur-name"
                        },
                        new
                        {
                            Id = 55,
                            IsoLanguageCode = "en",
                            LocalizedString = "13",
                            StringCode = "lupin-number"
                        },
                        new
                        {
                            Id = 56,
                            IsoLanguageCode = "en",
                            LocalizedString = "Lupin and products thereof",
                            StringCode = "lupin-name"
                        },
                        new
                        {
                            Id = 57,
                            IsoLanguageCode = "en",
                            LocalizedString = "14",
                            StringCode = "molluscs-number"
                        },
                        new
                        {
                            Id = 58,
                            IsoLanguageCode = "en",
                            LocalizedString = "Molluscs and products thereof",
                            StringCode = "molluscs-name"
                        },
                        new
                        {
                            Id = 59,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Upraviť reštauráciu",
                            StringCode = "update-restaurant-button"
                        },
                        new
                        {
                            Id = 60,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Pizza reštaurácia je miesto, kde si môžete objednať a vychutnať si chutnú pizzu s rôznymi polevami a prísadami. Reštaurácia obvykle ponúka aj iné jedlá ako napríklad cestoviny, šaláty, sendviče a rôzne nápoje. Väčšina pizza reštaurácií poskytuje aj možnosť objednania jedla na donášku alebo si ho môžete vyzdvihnúť na prevzatie. Atmosféra v reštaurácii je príjemná a obsluha je vždy ochotná pomôcť s výberom jedál alebo poradiť s výberom vín. Pizza reštaurácia je ideálne miesto pre rodinné večere, spoločné stretnutia s priateľmi alebo len tak na rýchle občerstvenie.",
                            StringCode = "restaurant-description"
                        },
                        new
                        {
                            Id = 61,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Kontakty",
                            StringCode = "restaurant-contacts"
                        },
                        new
                        {
                            Id = 62,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Adresa",
                            StringCode = "restaurant-address"
                        },
                        new
                        {
                            Id = 63,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Telefón",
                            StringCode = "restaurant-phone"
                        },
                        new
                        {
                            Id = 64,
                            IsoLanguageCode = "sk",
                            LocalizedString = "E-mail",
                            StringCode = "email"
                        },
                        new
                        {
                            Id = 65,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Kontaktujte nás",
                            StringCode = "restaurant-contact-us"
                        },
                        new
                        {
                            Id = 66,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Meno",
                            StringCode = "name"
                        },
                        new
                        {
                            Id = 67,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Správa",
                            StringCode = "restaurant-message"
                        },
                        new
                        {
                            Id = 69,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Odoslať",
                            StringCode = "submit-form-button"
                        },
                        new
                        {
                            Id = 71,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Heslo",
                            StringCode = "password"
                        },
                        new
                        {
                            Id = 73,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Vaše meno",
                            StringCode = "contact-form-name"
                        },
                        new
                        {
                            Id = 74,
                            IsoLanguageCode = "sk",
                            LocalizedString = "meno@mail.com",
                            StringCode = "contact-form-email"
                        },
                        new
                        {
                            Id = 79,
                            IsoLanguageCode = "en",
                            LocalizedString = "Edit restaurant",
                            StringCode = "update-restaurant-button"
                        },
                        new
                        {
                            Id = 80,
                            IsoLanguageCode = "en",
                            LocalizedString = "A pizza restaurant is a place where you can order and enjoy a delicious pizza with various toppings and ingredients. The restaurant typically also offers other dishes such as pasta, salads, sandwiches, and various drinks. Many pizza restaurants also offer the option to order food for delivery or pick it up for takeout. The atmosphere in the restaurant is usually pleasant and the staff is always willing to help with selecting dishes or recommending a wine pairing. A pizza restaurant is the perfect place for a family dinner, a gathering with friends, or just a quick bite to eat.",
                            StringCode = "restaurant-description"
                        },
                        new
                        {
                            Id = 81,
                            IsoLanguageCode = "en",
                            LocalizedString = "Contacts",
                            StringCode = "restaurant-contacts"
                        },
                        new
                        {
                            Id = 82,
                            IsoLanguageCode = "en",
                            LocalizedString = "Address",
                            StringCode = "restaurant-address"
                        },
                        new
                        {
                            Id = 83,
                            IsoLanguageCode = "en",
                            LocalizedString = "Phone",
                            StringCode = "restaurant-phone"
                        },
                        new
                        {
                            Id = 84,
                            IsoLanguageCode = "en",
                            LocalizedString = "E-mail",
                            StringCode = "email"
                        },
                        new
                        {
                            Id = 85,
                            IsoLanguageCode = "en",
                            LocalizedString = "Contact us",
                            StringCode = "restaurant-contact-us"
                        },
                        new
                        {
                            Id = 86,
                            IsoLanguageCode = "en",
                            LocalizedString = "Name",
                            StringCode = "name"
                        },
                        new
                        {
                            Id = 87,
                            IsoLanguageCode = "en",
                            LocalizedString = "Message",
                            StringCode = "restaurant-message"
                        },
                        new
                        {
                            Id = 89,
                            IsoLanguageCode = "en",
                            LocalizedString = "Send",
                            StringCode = "submit-form-button"
                        },
                        new
                        {
                            Id = 91,
                            IsoLanguageCode = "en",
                            LocalizedString = "Password",
                            StringCode = "password"
                        },
                        new
                        {
                            Id = 93,
                            IsoLanguageCode = "en",
                            LocalizedString = "Your name",
                            StringCode = "contact-form-name"
                        },
                        new
                        {
                            Id = 94,
                            IsoLanguageCode = "en",
                            LocalizedString = "name@mail.com",
                            StringCode = "contact-form-email"
                        },
                        new
                        {
                            Id = 99,
                            IsoLanguageCode = "en",
                            LocalizedString = "Create New",
                            StringCode = "create-drink"
                        },
                        new
                        {
                            Id = 100,
                            IsoLanguageCode = "en",
                            LocalizedString = "Name",
                            StringCode = "drink-name"
                        },
                        new
                        {
                            Id = 101,
                            IsoLanguageCode = "en",
                            LocalizedString = "Volume",
                            StringCode = "drink-volume"
                        },
                        new
                        {
                            Id = 102,
                            IsoLanguageCode = "en",
                            LocalizedString = "Price",
                            StringCode = "drink-price"
                        },
                        new
                        {
                            Id = 103,
                            IsoLanguageCode = "en",
                            LocalizedString = "Details",
                            StringCode = "drink-details"
                        },
                        new
                        {
                            Id = 104,
                            IsoLanguageCode = "en",
                            LocalizedString = "Edit",
                            StringCode = "drink-edit"
                        },
                        new
                        {
                            Id = 105,
                            IsoLanguageCode = "en",
                            LocalizedString = "Delete",
                            StringCode = "drink-delete"
                        },
                        new
                        {
                            Id = 106,
                            IsoLanguageCode = "en",
                            LocalizedString = "Back",
                            StringCode = "drink-back"
                        },
                        new
                        {
                            Id = 1009,
                            IsoLanguageCode = "en",
                            LocalizedString = "Drink",
                            StringCode = "drink"
                        },
                        new
                        {
                            Id = 1010,
                            IsoLanguageCode = "en",
                            LocalizedString = "Drinks",
                            StringCode = "drinks"
                        },
                        new
                        {
                            Id = 107,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Vytvoriť",
                            StringCode = "create-drink"
                        },
                        new
                        {
                            Id = 108,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Meno",
                            StringCode = "drink-name"
                        },
                        new
                        {
                            Id = 109,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Objem",
                            StringCode = "drink-volume"
                        },
                        new
                        {
                            Id = 110,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Cena",
                            StringCode = "drink-price"
                        },
                        new
                        {
                            Id = 111,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Podrobnosti",
                            StringCode = "drink-details"
                        },
                        new
                        {
                            Id = 112,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Upraviť",
                            StringCode = "drink-edit"
                        },
                        new
                        {
                            Id = 113,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Vymazať",
                            StringCode = "drink-delete"
                        },
                        new
                        {
                            Id = 114,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Späť",
                            StringCode = "drink-back"
                        },
                        new
                        {
                            Id = 1007,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Nápoj",
                            StringCode = "drink"
                        },
                        new
                        {
                            Id = 1008,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Nápoje",
                            StringCode = "drinks"
                        },
                        new
                        {
                            Id = 115,
                            IsoLanguageCode = "en",
                            LocalizedString = "Create New",
                            StringCode = "create-meal"
                        },
                        new
                        {
                            Id = 116,
                            IsoLanguageCode = "en",
                            LocalizedString = "Name",
                            StringCode = "meal-name"
                        },
                        new
                        {
                            Id = 117,
                            IsoLanguageCode = "en",
                            LocalizedString = "Price",
                            StringCode = "meal-price"
                        },
                        new
                        {
                            Id = 118,
                            IsoLanguageCode = "en",
                            LocalizedString = "Details",
                            StringCode = "meal-details"
                        },
                        new
                        {
                            Id = 119,
                            IsoLanguageCode = "en",
                            LocalizedString = "Edit",
                            StringCode = "meal-edit"
                        },
                        new
                        {
                            Id = 120,
                            IsoLanguageCode = "en",
                            LocalizedString = "Delete",
                            StringCode = "meal-delete"
                        },
                        new
                        {
                            Id = 121,
                            IsoLanguageCode = "en",
                            LocalizedString = "Back",
                            StringCode = "meal-back"
                        },
                        new
                        {
                            Id = 122,
                            IsoLanguageCode = "en",
                            LocalizedString = "Description",
                            StringCode = "meal-description"
                        },
                        new
                        {
                            Id = 123,
                            IsoLanguageCode = "en",
                            LocalizedString = "Allergens",
                            StringCode = "meal-allergens"
                        },
                        new
                        {
                            Id = 124,
                            IsoLanguageCode = "en",
                            LocalizedString = " - Write number of allergen separated by space, expect for last allergen",
                            StringCode = "meal-allergensDesctption"
                        },
                        new
                        {
                            Id = 125,
                            IsoLanguageCode = "en",
                            LocalizedString = " - Write link to picture",
                            StringCode = "meal-pictureDescription"
                        },
                        new
                        {
                            Id = 1002,
                            IsoLanguageCode = "en",
                            LocalizedString = "Meals",
                            StringCode = "meal"
                        },
                        new
                        {
                            Id = 1004,
                            IsoLanguageCode = "en",
                            LocalizedString = "Meal",
                            StringCode = "meal-single"
                        },
                        new
                        {
                            Id = 1006,
                            IsoLanguageCode = "en",
                            LocalizedString = "Picture",
                            StringCode = "meal-picture"
                        },
                        new
                        {
                            Id = 126,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Vytvoriť",
                            StringCode = "create-meal"
                        },
                        new
                        {
                            Id = 127,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Meno",
                            StringCode = "meal-name"
                        },
                        new
                        {
                            Id = 128,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Cena",
                            StringCode = "meal-price"
                        },
                        new
                        {
                            Id = 129,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Podprobnosti",
                            StringCode = "meal-details"
                        },
                        new
                        {
                            Id = 130,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Upraviť",
                            StringCode = "meal-edit"
                        },
                        new
                        {
                            Id = 131,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Vymazať",
                            StringCode = "meal-delete"
                        },
                        new
                        {
                            Id = 132,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Späť",
                            StringCode = "meal-back"
                        },
                        new
                        {
                            Id = 133,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Popis",
                            StringCode = "meal-description"
                        },
                        new
                        {
                            Id = 134,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Alergény",
                            StringCode = "meal-allergens"
                        },
                        new
                        {
                            Id = 135,
                            IsoLanguageCode = "sk",
                            LocalizedString = " - Napíšte číslo alergénu oddelené medzerou, okrem posledného alegénu",
                            StringCode = "meal-allergensDesctption"
                        },
                        new
                        {
                            Id = 136,
                            IsoLanguageCode = "sk",
                            LocalizedString = " - Vložte link na obrázok",
                            StringCode = "meal-pictureDescription"
                        },
                        new
                        {
                            Id = 1001,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Jedlá",
                            StringCode = "meal"
                        },
                        new
                        {
                            Id = 1003,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Jedlo",
                            StringCode = "meal-single"
                        },
                        new
                        {
                            Id = 1005,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Obrázok",
                            StringCode = "meal-picture"
                        },
                        new
                        {
                            Id = 2000,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Lokalizácia",
                            StringCode = "localization"
                        },
                        new
                        {
                            Id = 2002,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Vytvoriť",
                            StringCode = "localization-create"
                        },
                        new
                        {
                            Id = 2004,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Jazykový Kód Iso",
                            StringCode = "localization-iso"
                        },
                        new
                        {
                            Id = 2006,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Kód textu",
                            StringCode = "localization-stringcode"
                        },
                        new
                        {
                            Id = 2008,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Lokalizovaný text",
                            StringCode = "localization-localizedsting"
                        },
                        new
                        {
                            Id = 2010,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Vymazať",
                            StringCode = "localization-delete"
                        },
                        new
                        {
                            Id = 2012,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Upraviť",
                            StringCode = "localization-edit"
                        },
                        new
                        {
                            Id = 2001,
                            IsoLanguageCode = "en",
                            LocalizedString = "Localization",
                            StringCode = "localization"
                        },
                        new
                        {
                            Id = 2003,
                            IsoLanguageCode = "en",
                            LocalizedString = "Create",
                            StringCode = "localization-create"
                        },
                        new
                        {
                            Id = 2005,
                            IsoLanguageCode = "en",
                            LocalizedString = "Iso Language Code",
                            StringCode = "localization-iso"
                        },
                        new
                        {
                            Id = 2007,
                            IsoLanguageCode = "en",
                            LocalizedString = "String code",
                            StringCode = "localization-stringcode"
                        },
                        new
                        {
                            Id = 2009,
                            IsoLanguageCode = "en",
                            LocalizedString = "Localized string",
                            StringCode = "localization-localizedsting"
                        },
                        new
                        {
                            Id = 2011,
                            IsoLanguageCode = "en",
                            LocalizedString = "Delete",
                            StringCode = "localization-delete"
                        },
                        new
                        {
                            Id = 2013,
                            IsoLanguageCode = "en",
                            LocalizedString = "Edit",
                            StringCode = "localization-edit"
                        },
                        new
                        {
                            Id = 350,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Týždeň",
                            StringCode = "daily-menu-week"
                        },
                        new
                        {
                            Id = 352,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Dátum",
                            StringCode = "daily-menu-date"
                        },
                        new
                        {
                            Id = 353,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Deň",
                            StringCode = "daily-menu-day"
                        },
                        new
                        {
                            Id = 354,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Cena",
                            StringCode = "daily-menu-price"
                        },
                        new
                        {
                            Id = 355,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Jedlo",
                            StringCode = "daily-menu-meal"
                        },
                        new
                        {
                            Id = 356,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Dátum (od - do)",
                            StringCode = "weekly-menu-date"
                        },
                        new
                        {
                            Id = 357,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Ľutujeme, pre tento týždeň neponúkame žiadne meníčka.",
                            StringCode = "no-weekly-menus"
                        },
                        new
                        {
                            Id = 358,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Dátum (Od)",
                            StringCode = "weekly-menu-date-from"
                        },
                        new
                        {
                            Id = 359,
                            IsoLanguageCode = "sk",
                            LocalizedString = "Dátum(Do)",
                            StringCode = "weekly-menu-date-to"
                        },
                        new
                        {
                            Id = 300,
                            IsoLanguageCode = "en",
                            LocalizedString = "Week",
                            StringCode = "daily-menu-week"
                        },
                        new
                        {
                            Id = 302,
                            IsoLanguageCode = "en",
                            LocalizedString = "Date",
                            StringCode = "daily-menu-date"
                        },
                        new
                        {
                            Id = 303,
                            IsoLanguageCode = "en",
                            LocalizedString = "Day",
                            StringCode = "daily-menu-day"
                        },
                        new
                        {
                            Id = 304,
                            IsoLanguageCode = "en",
                            LocalizedString = "Price",
                            StringCode = "daily-menu-price"
                        },
                        new
                        {
                            Id = 305,
                            IsoLanguageCode = "en",
                            LocalizedString = "Meal",
                            StringCode = "daily-menu-meal"
                        },
                        new
                        {
                            Id = 307,
                            IsoLanguageCode = "en",
                            LocalizedString = "Date (start - end)",
                            StringCode = "weekly-menu-date"
                        },
                        new
                        {
                            Id = 308,
                            IsoLanguageCode = "en",
                            LocalizedString = "We apologize, there are currently no weekly menus offered for this date",
                            StringCode = "no-weekly-menus"
                        },
                        new
                        {
                            Id = 309,
                            IsoLanguageCode = "en",
                            LocalizedString = "Date From",
                            StringCode = "weekly-menu-date-from"
                        },
                        new
                        {
                            Id = 310,
                            IsoLanguageCode = "en",
                            LocalizedString = "Date To",
                            StringCode = "weekly-menu-date-to"
                        });
                });

            modelBuilder.Entity("RestaurantWebDAL.Models.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AllergenFlags")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("RestaurantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Meal");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllergenFlags = 65,
                            Description = "Tomato, Cheese, Ham, Mushrooms",
                            Name = "Capri",
                            Picture = "https://i.imgur.com/BH6YDXe.jpeg",
                            Price = 6.35m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 2,
                            AllergenFlags = 65,
                            Description = "Tomato, Cheese, Ham, Pineapple",
                            Name = "Hawai",
                            Picture = "https://i.imgur.com/1Urm6EY.jpeg",
                            Price = 8.99m,
                            RestaurantId = 1
                        });
                });

            modelBuilder.Entity("RestaurantWebDAL.Models.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Restaurant");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Hlavna 65 080 01 Prešov",
                            Description = "A pizza restaurant is a place where you can order and enjoy a delicious pizza with various toppings and ingredients. The restaurant typically also offers other dishes such as pasta, salads, sandwiches, and various drinks. Many pizza restaurants also offer the option to order food for delivery or pick it up for takeout. The atmosphere in the restaurant is usually pleasant and the staff is always willing to help with selecting dishes or recommending a wine pairing. A pizza restaurant is the perfect place for a family dinner, a gathering with friends, or just a quick bite to eat.",
                            Email = "marcorestaurant@marcorestaurant.com",
                            Latitude = "49.2099917",
                            Longitude = "16.598866360931357",
                            Name = "Marco Restaurant",
                            Phone = "0917123456"
                        });
                });

            modelBuilder.Entity("RestaurantWebDAL.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3b2b98cb-5a7d-4c40-82cb-342f72014bfb",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fa400435-6389-4ae8-b9a8-6bcc6331d100",
                            Email = "lazorik.juraj@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Gordon",
                            LastName = "Ramsay",
                            LockoutEnabled = false,
                            NormalizedEmail = "LAZORIK.JURAJ@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEOKVJsSevM2wlg1c7EJcWMDMkZxa2Nvs/f1w3v68wjEszGhQnX1guG5IFDA/1LSc6w==",
                            PhoneNumber = "0917123456",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("RestaurantWebDAL.Models.WeeklyMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("DATE");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("DATE");

                    b.HasKey("Id");

                    b.ToTable("WeeklyMenu");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateFrom = new DateTime(2022, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTo = new DateTime(2022, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            DateFrom = new DateTime(2022, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTo = new DateTime(2023, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("RestaurantWebDAL.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("RestaurantWebDAL.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantWebDAL.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("RestaurantWebDAL.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestaurantWebDAL.Models.DailyMenu", b =>
                {
                    b.HasOne("RestaurantWebDAL.Models.Meal", "Meal")
                        .WithMany()
                        .HasForeignKey("MealId");

                    b.HasOne("RestaurantWebDAL.Models.WeeklyMenu", "WeeklyMenu")
                        .WithMany()
                        .HasForeignKey("WeeklyMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");

                    b.Navigation("WeeklyMenu");
                });

            modelBuilder.Entity("RestaurantWebDAL.Models.Drink", b =>
                {
                    b.HasOne("RestaurantWebDAL.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("RestaurantWebDAL.Models.Meal", b =>
                {
                    b.HasOne("RestaurantWebDAL.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId");

                    b.Navigation("Restaurant");
                });
#pragma warning restore 612, 618
        }
    }
}
